# Praktikum 2: Komputasi Numerik dengan NumPy Array

<a href="https://colab.research.google.com/github/pakizhan-ump/ml-umpontianak/blob/main/Modules/Week-02/Praktikum-02/Praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🎯 Tujuan Praktikum
Mahasiswa mampu menggunakan library **NumPy** untuk membuat dan memanipulasi array multidimensi serta memahami keunggulannya dibandingkan List untuk komputasi numerik.

## 📖 Dasar Teori
**NumPy (Numerical Python)** adalah library fundamental untuk komputasi ilmiah di Python. Struktur data utamanya adalah **ndarray (n-dimensional array)**, yang dirancang khusus untuk operasi numerik yang efisien. Keunggulan utamanya meliputi:
* **Homogeneous:** Semua elemen dalam sebuah array harus memiliki tipe data yang sama (misalnya, semua `float64` atau semua `int32`), yang memungkinkan penyimpanan memori yang lebih efisien.
* **Ukuran Tetap:** Ukuran array ditentukan saat pembuatan, membuatnya lebih dapat diprediksi dalam hal alokasi memori.
* **Efisiensi Memori & Kecepatan:** Operasi matematika pada NumPy array jauh lebih cepat karena dieksekusi oleh kode C yang terkompilasi, bukan melalui interpreter Python.
* **Mendukung Operasi Vektorisasi:** Memungkinkan operasi matematika dilakukan pada seluruh elemen array secara bersamaan tanpa perlu menulis *loop* `for`, membuat kode lebih ringkas dan cepat.

Dalam machine learning, data seperti gambar (matriks piksel), sinyal audio, atau fitur-fitur numerik hampir selalu direpresentasikan sebagai NumPy array.

In [2]:
import numpy as np

# 🔧 OPERASI FUNDAMENTAL NUMPY

# 1. ARRAY CREATION & TYPES

In [3]:
print("=== ARRAY CREATION ===")
arr1d = np.array([1, 2, 3, 4, 5])                    # 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])            # 2D array
arr3d = np.random.rand(2, 3, 4)                     # 3D random array

print("1D array shape:", arr1d.shape)
print("2D array shape:", arr2d.shape)
print("3D array shape:", arr3d.shape)

=== ARRAY CREATION ===
1D array shape: (5,)
2D array shape: (2, 3)
3D array shape: (2, 3, 4)


# 2. DATA TYPES

In [4]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
arr_bool = np.array([True, False, True])

print("Data types:")
print("arr_int dtype:", arr_int.dtype)
print("arr_float dtype:", arr_float.dtype)

Data types:
arr_int dtype: int32
arr_float dtype: float64


# 3. ACCESS & SLICING

In [5]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])

print("\n=== ACCESS & SLICING ===")
print("Element [1,2]:", matrix[1, 2])                # Single element
print("Row 1:", matrix[1, :])                        # Entire row
print("Column 2:", matrix[:, 2])                     # Entire column
print("Submatrix 2x2:\n", matrix[0:2, 1:3])          # Submatrix
print("Every other row:\n", matrix[::2, :])          # Step slicing


=== ACCESS & SLICING ===
Element [1,2]: 7
Row 1: [5 6 7 8]
Column 2: [ 3  7 11]
Submatrix 2x2:
 [[2 3]
 [6 7]]
Every other row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


# 4. RESHAPING

In [6]:
print("\n=== RESHAPING ===")
arr = np.arange(12)                                  # 0-11
print("Original shape:", arr.shape)
reshaped = arr.reshape(3, 4)                        # Reshape to 3x4
flattened = reshaped.flatten()                      # Back to 1D
transposed = reshaped.T                             # Transpose

print("Reshaped 3x4:\n", reshaped)
print("Transposed 4x3:\n", transposed)
print("Flattened:", flattened)


=== RESHAPING ===
Original shape: (12,)
Reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed 4x3:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


# 5. MATHEMATICAL OPERATIONS

In [7]:
print("\n=== MATHEMATICAL OPERATIONS ===")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)                             # Element-wise add
print("a * b =", a * b)                             # Element-wise multiply
print("a ** 2 =", a ** 2)                           # Power
print("np.dot(a, b) =", np.dot(a, b))               # Dot product


=== MATHEMATICAL OPERATIONS ===
a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]
np.dot(a, b) = 32


# 6. AGGREGATION

In [8]:
print("\n=== AGGREGATION ===")
data = np.random.rand(5, 4)                         # 5x4 random data
print("Data:\n", data)
print("Sum all:", np.sum(data))
print("Mean all:", np.mean(data))
print("Std all:", np.std(data))
print("Sum columns:", np.sum(data, axis=0))         # Along columns
print("Mean rows:", np.mean(data, axis=1))          # Along rows


=== AGGREGATION ===
Data:
 [[0.65436587 0.30653796 0.9837402  0.82771076]
 [0.42555359 0.36523737 0.26438848 0.19450607]
 [0.53515894 0.77261207 0.0618182  0.52880534]
 [0.62568771 0.52344915 0.95711637 0.53972394]
 [0.56422772 0.44089437 0.91095005 0.90565544]]
Sum all: 11.388139597792106
Mean all: 0.5694069798896053
Std all: 0.25643453448811193
Sum columns: [2.80499384 2.40873091 3.1780133  2.99640155]
Mean rows: [0.6930887  0.31242138 0.47459864 0.66149429 0.7054319 ]


# 7. BROADCASTING

In [9]:
print("\n=== BROADCASTING ===")
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector                            # Broadcasting
print("Matrix + Vector:\n", result)


=== BROADCASTING ===
Matrix + Vector:
 [[11 22 33]
 [14 25 36]]


# 8. RANDOM OPERATIONS

In [10]:
print("\n=== RANDOM OPERATIONS ===")
random_arr = np.random.rand(3, 3)                   # Uniform [0,1)
normal_arr = np.random.randn(3, 3)                  # Normal distribution
integers = np.random.randint(0, 100, (3, 3))        # Random integers

print("Uniform random:\n", random_arr)
print("Normal random:\n", normal_arr)
print("Random integers:\n", integers)


=== RANDOM OPERATIONS ===
Uniform random:
 [[0.22563161 0.54285845 0.67887357]
 [0.85934237 0.09448316 0.38584226]
 [0.59216269 0.58912829 0.8555764 ]]
Normal random:
 [[ 0.46022442 -1.34672017 -0.90816816]
 [ 1.40266827 -1.12749173  1.11115461]
 [ 2.20576089 -0.87066288  1.73833131]]
Random integers:
 [[93  6 65]
 [12 18 92]
 [80 25 27]]


# 9. SPLITTING & JOINING

In [11]:
print("\n=== SPLITTING & JOINING ===")
arr = np.arange(12).reshape(3, 4)
sub_arrays = np.split(arr, 3, axis=0)               # Split along rows
print("Original:\n", arr)
print("After split:")
for i, sub in enumerate(sub_arrays):
    print(f"Part {i}:\n{sub}")

# Joining arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
joined = np.concatenate([arr1, arr2], axis=0)       # Vertical join
print("After concatenation:\n", joined)


=== SPLITTING & JOINING ===
Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After split:
Part 0:
[[0 1 2 3]]
Part 1:
[[4 5 6 7]]
Part 2:
[[ 8  9 10 11]]
After concatenation:
 [[1 2]
 [3 4]
 [5 6]]


# 10. CONDITIONAL OPERATIONS

In [12]:
print("\n=== CONDITIONAL OPERATIONS ===")
data = np.array([10, 25, 30, 45, 50, 65])
mask = data > 30                                    # Boolean mask
filtered = data[mask]                               # Filter with mask
print("Data > 30:", filtered)

# Where operation
result = np.where(data > 30, data, 0)               # Replace conditionally
print("Where > 30 else 0:", result)


=== CONDITIONAL OPERATIONS ===
Data > 30: [45 50 65]
Where > 30 else 0: [ 0  0  0 45 50 65]


# 🏋️ LATIHAN 2: OPERASI NUMPY UNTUK MACHINE LEARNING

### DATA PREPROCESSING DENGAN NUMPY ###

In [ ]:
'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

# TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    # TODO: Implementasi Z-score normalization
    pass

X_normalized = z_score_normalization(X)

# TODO 2: Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    # TODO: Handle outliers using std threshold
    pass

X_cleaned = handle_outliers(X_normalized)

# TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    # TODO: Convert categorical labels to one-hot encoding
    # Input: [0, 1, 2, 0, 1] -> Output: 2D one-hot array
    pass

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2):
    # TODO: Implementasi train-test split tanpa sklearn
    pass

X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"
print("✅ NumPy operations completed")